#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`


In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`


In [3]:
# 
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`


In [4]:
null_vect = np.zeros(10)
null_vect[4] = 1
print(null_vect)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`


In [5]:
vect = np.arange(10,50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [6]:
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [7]:
non_zero = [1,2,0,0,4,0]
np.nonzero(non_zero)

(array([0, 1, 4]),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [8]:
matrix1 = np.eye(3,3)
print(matrix1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [9]:
np.random.seed(10)
rand_val = np.random.random((3,3))
print(rand_val)



[[0.77132064 0.02075195 0.63364823]
 [0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [38]:
np.random.seed(11)
array_val = np.random.random((10,10))
minimum_val = array_val.min()
maximum_val = array_val.max()
print('The minimum value is: {}'.format(minimum_val), "\n")
print('The maximum value is: {}'.format(maximum_val), "\n")

The minimum value is: 0.012780814590608647 

The maximum value is: 0.9866733303584686 



#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [11]:
rand_vector = np.arange(31)
print(rand_vector, "\n")

rand_vector_mean = np.mean(rand_vector)
print(round(rand_vector_mean, 2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30] 

15.0


#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [12]:
matrix5 = np.arange(5)#.reshape(5,5)
matrix5
new_matrix5 = np.diag(matrix5)
print(new_matrix5)


[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [12]:
norm_mat = np.random.randint(50, size=(5,5))
norm_mat_max, norm_mat_min = norm_mat.max(), norm_mat.min()
norm_mat = (norm_mat - norm_mat_min)/(norm_mat_max - norm_mat_min)
print(norm_mat)

[[0.29787234 0.36170213 0.06382979 0.9787234  0.29787234]
 [0.85106383 0.         0.40425532 0.72340426 1.        ]
 [0.95744681 0.82978723 0.25531915 0.74468085 0.57446809]
 [0.23404255 0.36170213 0.23404255 0.68085106 0.46808511]
 [0.10638298 0.87234043 0.12765957 0.72340426 1.        ]]


#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [33]:
first_array = np.arange(6,15).reshape(3,3)
second_array = np.arange(0,9).reshape(3,3)
np.intersect1d(first_array, second_array)

array([6, 7, 8])

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [39]:
random_vector = np.random.random((10))
print(random_vector)
np.sort(random_vector)

[0.31818719 0.21800338 0.84493853 0.30216469 0.43822067 0.09141459
 0.30097917 0.08569481 0.34371331 0.70930102]


array([0.08569481, 0.09141459, 0.21800338, 0.30097917, 0.30216469,
       0.31818719, 0.34371331, 0.43822067, 0.70930102, 0.84493853])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [5]:
np.random.seed(100)
my_max = np.random.random((10))
my_max[my_max.argmax()] = 0
print(my_max)
        
        
        

[0.54340494 0.27836939 0.42451759 0.         0.00471886 0.12156912
 0.67074908 0.82585276 0.13670659 0.57509333]


#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [52]:
np.random.seed(1000)
a = np.random.random((3,4))
print(a, "\n")
b = a-a.mean(axis=1, keepdims = True)
b

[[0.65358959 0.11500694 0.95028286 0.4821914 ]
 [0.87247454 0.21233268 0.04070962 0.39719446]
 [0.2331322  0.84174072 0.20708234 0.74246953]] 



array([[ 0.10332189, -0.43526076,  0.40001517, -0.0680763 ],
       [ 0.49179671, -0.16834514, -0.3399682 ,  0.01651664],
       [-0.272974  ,  0.33563452, -0.29902386,  0.23636333]])

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition

In [9]:
Z = np.arange(10000)
np.random.shuffle(Z) 
n = 5
np.argsort(Z)
ind = np.argpartition(Z, 5)[5:]
# ind = np.argpartition(Z,5)
print(ind)


[6367 6628 7630 ...   34   32 9999]


#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [68]:
np.random.seed(1111)
#x = np.random.random(6,size=5,3) #doesnt work, no reason why
x = np.random.randint(10, size=(5, 3))
print(x)
np.where(x < 4, x, x**2)

[[7 5 1]
 [2 4 8]
 [6 4 8]
 [6 2 6]
 [8 9 3]]


array([[49, 25,  1],
       [ 2, 16, 64],
       [36, 16, 64],
       [36,  2, 36],
       [64, 81,  3]])